In [ ]:
#py_basic_programming_asgn_8


In [ ]:
1.	Write a Python Program to Add Two Matrices?



In [17]:
import numpy as np

a = np.matrix([[1,2,3],[2,5,6],[5,9,8]])

b = np.matrix([[9,2,3],[7,5,6],[6,9,8]])

c= np.matrix([[0,0,0],[0,0,0],[0,0,0]])

for i in range(len(a)):
    for j in range(len(a[0])):
        c[i][j]= a[i][j]+b[i][j]
    

for x in c:
    print(x)

[[10  4  6]]
[[ 9 10 12]]
[[11 18 16]]


In [ ]:
2.	Write a Python Program to Multiply Two Matrices?


In [18]:
# 3x3 matrix
X = [[12,7,3],
    [4 ,5,6],
    [7 ,8,9]]
# 3x4 matrix
Y = [[5,8,1,2],
    [6,7,3,0],
    [4,5,9,1]]
# result is 3x4
result = [[0,0,0,0],
         [0,0,0,0],
         [0,0,0,0]]

# iterate through rows of X
for i in range(len(X)):
   # iterate through columns of Y
   for j in range(len(Y[0])):
       # iterate through rows of Y
       for k in range(len(Y)):
           result[i][j] += X[i][k] * Y[k][j]

for r in result:
   print(r)

[114, 160, 60, 27]
[74, 97, 73, 14]
[119, 157, 112, 23]


In [ ]:
3.	Write a Python Program to Transpose a Matrix?


In [22]:
# Program to transpose a matrix using a nested loop

X = [[12,7],
    [4 ,5],
    [3 ,8]]

result = [[0,0,0],
         [0,0,0]]

# iterate through rows
for i in range(len(X)):
   # iterate through columns
   for j in range(len(X[0])):
       result[j][i] = X[i][j]

for r in result:
   print(r)

[12, 4, 3]
[7, 5, 8]


In [ ]:
4.	Write a Python Program to Sort Words in Alphabetic Order?


In [11]:
ex_str= "hello how are you hope you are good"

words = [word.lower() for word in ex_str.split()]

words.sort()

print("The sorted words are:")
for word in words:
    print(word)

The sorted words are:
are
are
good
hello
hope
how
you
you


In [ ]:
5.	Write a Python Program to Remove Punctuation From a String?

In [12]:
# define punctuation
punctuations = '''!()-[]{};:'"\,<>./?@#$%^&*_~'''

my_str = "Hello!!!, he is good ---too good."

# To take input from the user
# my_str = input("Enter a string: ")

# remove punctuation from the string
no_punct = ""
for char in my_str:
   if char not in punctuations:
       no_punct = no_punct + char

# display the unpunctuated string
print(no_punct)

Hello he is good too good
